# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Frontend build and push to s3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install-and-build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.19.1

      - name: Install Dependencies
        run: yarn install

      - name: Build Frontend
        run: yarn build

  deploy_to_s3:
    runs-on: self-hosted
    needs: [install-and-build]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to S3 Bucket
        uses: jakejarvis/s3-sync-action@master
        with:
           args: --delete --exclude '.git/*' dist/
           bucket_url: s3://subash-frontend
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

          run: |
            aws s3 sync dist/ s3://${AWS_S3_BUCKET}/ --delete

      
